# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6449404cf6222829f2e20bac430c4d659b47318a8d5cf9f8659f8fa7220cc9be963a23eda82dc325a5e1655d3e0db6fe2bc6d8a9896ff7fe99233401c9d223c6

test:
  secret_key_base: 81695c1b9b9f979c5ca7b82c685b7c5294a9a6ed11d7a1f66af349dab4ecd6aca7b8fbcb20376d4c9be83fbc125e5697378ea5f8e3bccf458627a8d283bc48a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
